
# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Scala CI


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  #contents: read, write
  contents: write # this permission is needed to submit the dependency graph

env:
  build-number: ${GITHUB_RUN_NUMBER}

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'sbt'

      - uses: sbt/setup-sbt@v1

      - name: Release Artifact Uploads
        run:
          -|
          sbt "set test in assembly := {}" clean assembly
          mkdir staging && for FILENAME in $(ls target/*/*.jar); do  NEWFILENAME=$(sed -E "s/-SNAPSHOT.jar/.jar/g" <<< $(basename "$FILENAME")); mv "$FILENAME" staging/"$NEWFILENAME"; done;

      - uses: actions/upload-artifact@v4
        with:
          name: Package
          path: staging
          retention-days: 1

#      - uses: marvinpinto/action-automatic-releases@latest
#        with:
#          repo_token: "${{ secrets.YOUR-GITHUB-TOKEN }}"
#          automatic_release_tag: "${{ github.run_number }}"
#          title: "Automated Build ${{ github.run_number }}"
#          prerelease: true
#          files: staging/*.jar